
network:
  version: 2
  renderer: networkd
  ethernets:
    enp2s0:
      dhcp4: false
  bridges:
    br0:
      interfaces: [enp2s0]
      dhcp4: false
      addresses: [192.168.0.57/24]
      gateway4: 192.168.0.1
      nameservers:
        addresses: [192.168.0.1]
